### PR TITLE
Added build script using BinDeps

### PR DESCRIPTION
**Pull request by stemann**
Using Compat for 0.3/0.4 compatibility.
Updated to use libvl shared library built by included build script.

### CODE REVIEW

**Comment by kmsquire** [comment]
Okay, I hadn't seen this PR before commenting on the last one.  Thanks for all of this!

It looks like #2 is included in this PR.  I'll take a look, and if everything is okay, merge.

**Comment by kmsquire** [comment]
@stemann, would you want to take over development of this package (and possibly register it)?

**Comment by stemann** [comment]
No problem. Thanks for merging.

Sure, I can take over. I'll have to look into how to version and register a package, but I guess all necessary info is in the docs.

**Comment by kmsquire** [comment]
Great!  Versioning and registering a package should be as simple as

``` julia
Pkg.update()
Pkg.register("VLFeat", <url>)
Pkg.tag("VLFeat")
Pkg.publish()
```

It would probably be good if I transferred this repo to you.  It preserves history (there's not much here), but more importantly, if I don't, then github sometimes gets confused with pull requests and tries to submit them "upstream" (i.e., to the original repo that you cloned from).  To transfer, you'll have to delete yours (on github).

**Comment by stemann** [comment]
OK - my repo is gone.

It should be transferred to @IHPostal

**Comment by kmsquire** [comment]
I can only transfer it to another user (i.e., you), or to an organization where I have admin rights.  It's probably easiest if I transfer it to you and you then transfer it to IHPostal, unless you want to temporarily give me admin rights on IHPostal.  Let me know. 

(I'll be heading to bed in about 10-15 minutes, so I'll transfer it when I wake up if I don't hear from you before then.)

**Comment by stemann** [comment]
Transfer to me is fine, then.

**Comment by kmsquire** [comment]
Okay, transfer initiated!  Not sure how long that takes, but at some point (soon) you should see the repo, and attempts to access the repo under my account will redirect to yours.

Good luck, and thanks for taking this on!

**Comment by stemann** [comment]
Great. And thanks to you!

**Pull request merged**
